### ISSUE TITLE
Pushing a 'ready' branch with no new commits fails with odd error message (case 14686)

### ISSUE THREAD

**Issue by praqma-thi** [Praqma/pretested-integration-plugin#15] opened 2016-02-25 09:37 UTC
## Squash strategy

I forgot to commit my staged changes before pushing my ready branch, thus I pushed a branch with no new commits on it (AKA equal to master).
Pretested Integration failed, but the reason of failure was seemingly unrelated.
We could handle this situation and return a better error message.

#### Console output
```
[PREINT] Not attempting fast forward. Exiting tryFastForward.
[PREINT] Preparing to merge changes in commit 624f94388c047d8ed8bbdf038f350c6d04ff6e58 on development branch origin/ready/improved-error-wording to integration branch master
[PREINT] Collecting author of last commit on development branch
[PREINT] Done colecting last commit author: ReleasePraqma <release@praqma.net> 1448884117 +0100
[PREINT] Starting squash merge - without commit:
[PREINT]  merge --squash origin/ready/improved-error-wording
 > git merge --squash 624f94388c047d8ed8bbdf038f350c6d04ff6e58 # timeout=10
[PREINT] Squash merge done
[PREINT] Merge was successful
[PREINT] Starting to commit squash merge changes:
[PREINT] Exception while committing. Logging exception msg: java.io.FileNotFoundException: /home/praqma/jenkinslave/workspace/memory-map-plugin_verify_(ready)_GEN/.git/SQUASH_MSG (No such file or directory)
[PREINT]  - setUp() - IntegrationFailedException - Merge failure
```

## Accumulated

Haven't tested but I know we don't catch this situation either.

**Comment by praqma-thi** [comment] 2016-04-05 11:45
@bicschneider confirms that the same issue occurs with the Accumulated strategy.

**Comment by praqma-thi** [comment] 2016-04-06 07:24
I pushed a branch `15-changeless-ready-branch-fails`.
It contains a test pointing out the failure for each strategy.

**Comment by buep** [comment] 2016-05-11 10:57
Since you already spent time on it, can you finish it within the estimate?
Including release etc.

I'm trying to clean up things, including this half-done issue.

**Comment by buep** [comment] 2016-06-07 07:11
We're jumping a version number in the changelog, but it seems there is a release called 2.4.1 so I need that in the changelog obviously... else no one will know what it contains.

This commit is also without issue reference? Please make sure every commit have issue references.
https://github.com/Praqma/pretested-integration-plugin/commit/b6d72e1de66468656466ec64345f8c809a7f10ae

And that we don't release something like a draft - according to your commit message "First draft for #15" 

And a few comments to the source code comparison between 2.4.0 and 2.4.2:

https://github.com/Praqma/pretested-integration-plugin/compare/pretested-integration-2.4.0...pretested-integration-2.4.2

* Why return a plugin not found when we can't resolve version? Should that be something like could resolve version? And how can this happen?
* Why don't I get the ex.getMessage() together with the new squash commit failure handling ? Line 150 i Accummulated strategy and around line 130 in squashed
* "We need to discuss what it SHOULD do, but I'm fairly sure it shouldn't fail with an odd message." is not any more a relevant comment to the tests... we have discussed that since it is implemented?


Also clean up old branch when done.

**Comment by buep** [comment] 2016-06-07 07:39
How can we even have a release when the release build failed? 

http://code.praqma.net/ci/job/pretested-integration-plugin_release-from-Github-Praqma_master/

http://code.praqma.net/ci/view/Open%20Source%20Pipelines/view/Pretested%20Integration%20Plugin%20-%20build%20pipeline/

**Comment by buep** [comment] 2016-06-09 12:54
What about my comments above? https://github.com/Praqma/pretested-integration-plugin/issues/15#issuecomment-224198612

Are they all handled?

**Comment by MadsNielsen** [comment] 2016-06-09 17:29
I guess the version thing is done because Netbeans complains a possible null pointer dereferencing. I do not see how it can happen in real use scenarios though, so the change is inconsequential. 

The implentation currently will give a much better explanation as to what went wrong, instead of FileNotFound exception, which will allow user to ignore the error when they see it. We can always decide to handle this in a more graceful way, this is a quick solution, that was supposed to be quite easy to implement and give better feedback to the user.

**Comment by buep** [comment] 2016-06-09 20:49
yes, I agree, but the three things I point out is very easy to fix. They are just adjusting to better message reporting error to the user and removing a old deprecated comment in the code.

These things are fairly easy to fix, at least on master and releasing them next time.

They are more about being consistent in reporting to the user, than about logic in the code. We should, even though the code is maintained by several people try to align it .... so if some error message report the exception, they all do.
And the exception about plugin not found, even though it might never happen, still doesn't really make sense to report as a version to the user.

**Comment by MadsNielsen** [comment] 2016-06-13 07:08
I've had a chat with @praqma-thi he'll comment on change with the version number. 

The second point you raised should be adressed in the commit. I include the original message in the error as well in the release. 

The 3rd point, i phrased it in such a way becuase i do not know if there are other errors which might be thrown that has the same error message. The exceptions thrown are so general that it's hard to spell out the cause, in such a way that the user understand it.

**Comment by praqma-thi** [comment] 2016-06-13 07:12
The `getPlugin("pretested-integration")` returned a null during testing.
I added a quick null-check as a workaround for that. 
The message I return might not be top tier, though.

**Comment by buep** [comment] 2016-06-13 07:59
My third point was about this line: https://github.com/Praqma/pretested-integration-plugin/blob/master/src/test/java/org/jenkinsci/plugins/pretestedintegration/integration/scm/git/ChangelessBranchFailsBuildIT.java#L17

Reword the comment, it is valuable information, but not any more a TODO!

Reword the message returned from plugin version loookup from "plugin-not-found" to e.g. "unknow version - plugin not found"

Make this changes, don't need a new release then close this issue.

**Closed** 2016-06-13 14:30 UTC
Labels: Prio 3 - could have, Size 2 - medium, Status - up Next

**Comment by emimarz** [comment] 2017-01-18 14:47
so, what's the news here? I have the same error and we are in 2017 several months past and the error continue
