### ISSUE TITLE
Fix current "integration test" due to Pipeline rework, robustness(especially Windows) and changed descriptions

### ISSUE THREAD

**Issue by bicschneider** [Praqma/pretested-integration-plugin#65] opened 2017-09-07 13:04 UTC
- Many test cases fails on Windows due to cleanup of temp repository. 
- Some fail due to changed description / console output
- Some test cases could be wrong

**Comment by groenborg** [comment] 2017-09-18 14:25
[INFO] Scanning for projects...
[WARNING] The POM for org.jenkins-ci.tools:maven-hpi-plugin:jar:1.106 is missing, no dependency information available
[WARNING] Failed to build parent project for org.jenkins-ci.plugins:pretested-integration:hpi:2.4.1
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building Pretested Integration Plugin 2.4.1
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.4.1:clean (default-clean) @ pretested-integration ---
[INFO] Deleting /Users/simon/Github/praqma/pretested-integration-plugin/target
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.635 s
[INFO] Finished at: 2017-09-18T16:00:44+02:00
[INFO] Final Memory: 14M/309M
[INFO] ------------------------------------------------------------------------
 
/Users/simon/Github/praqma/pretested-integration-plugin
simon@=Simons-MacBook-Pro-2 $ mvn install
[INFO] Scanning for projects...
[WARNING] The POM for org.jenkins-ci.tools:maven-hpi-plugin:jar:1.106 is missing, no dependency information available
[WARNING] Failed to build parent project for org.jenkins-ci.plugins:pretested-integration:hpi:2.4.1
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building Pretested Integration Plugin 2.4.1
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-hpi-plugin:1.115:validate (default-validate) @ pretested-integration ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.0.1:enforce (enforce-maven) @ pretested-integration ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.0.1:display-info (display-info) @ pretested-integration ---
[INFO] Maven Version: 3.5.0
[INFO] JDK Version: 1.8.0_131 normalized as: 1.8.0-131
[INFO] OS Info: Arch: x86_64 Family: mac Name: mac os x Version: 10.12.6
[INFO] 
[INFO] --- buildnumber-maven-plugin:1.3:create (default) @ pretested-integration ---
[INFO] ShortRevision tag detected. The value is '5'.
[INFO] Executing: /bin/sh -c cd /Users/simon/Github/praqma/pretested-integration-plugin && git rev-parse --verify --short=5 HEAD
[INFO] Working directory: /Users/simon/Github/praqma/pretested-integration-plugin
[INFO] Storing buildNumber: 409ae at timestamp: 1505743251722
[WARNING] Cannot get the branch information from the git repository: 
Detecting the current branch failed: fatal: ref HEAD is not a symbolic ref

[INFO] ShortRevision tag detected. The value is '5'.
[INFO] Executing: /bin/sh -c cd /Users/simon/Github/praqma/pretested-integration-plugin && git rev-parse --verify --short=5 HEAD
[INFO] Working directory: /Users/simon/Github/praqma/pretested-integration-plugin
[INFO] Storing buildScmBranch: UNKNOWN
[INFO] 
[INFO] --- maven-localizer-plugin:1.14:generate (default) @ pretested-integration ---
[INFO] 
[INFO] --- maven-resources-plugin:2.5:resources (default-resources) @ pretested-integration ---
[debug] execute contextualize
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 12 resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.5:compile (default-compile) @ pretested-integration ---
[INFO] Compiling 23 source files to /Users/simon/Github/praqma/pretested-integration-plugin/target/classes
[INFO] 
[INFO] --- access-modifier-checker:1.12:enforce (default-enforce) @ pretested-integration ---
[INFO] 
[INFO] --- maven-hpi-plugin:1.115:insert-test (default-insert-test) @ pretested-integration ---
[INFO] 
[INFO] --- gmaven-plugin:1.5-jenkins-1:generateTestStubs (test-in-groovy) @ pretested-integration ---
[INFO] No sources found for Java stub generation
[INFO] 
[INFO] --- maven-resources-plugin:2.5:testResources (default-testResources) @ pretested-integration ---
[debug] execute contextualize
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 26 resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.5:testCompile (default-testCompile) @ pretested-integration ---
[INFO] Compiling 33 source files to /Users/simon/Github/praqma/pretested-integration-plugin/target/test-classes
[INFO] 
[INFO] --- maven-hpi-plugin:1.115:test-hpl (default-test-hpl) @ pretested-integration ---
[INFO] Generating /Users/simon/Github/praqma/pretested-integration-plugin/target/test-classes/the.hpl
[INFO] 
[INFO] --- maven-hpi-plugin:1.115:resolve-test-dependencies (default-resolve-test-dependencies) @ pretested-integration ---
[INFO] 
[INFO] --- gmaven-plugin:1.5-jenkins-1:testCompile (test-in-groovy) @ pretested-integration ---
[INFO] No sources found to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.17:test (default-test) @ pretested-integration ---
[INFO] Surefire report directory: /Users/simon/Github/praqma/pretested-integration-plugin/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.jenkinsci.plugins.pretestedintegration.PretestedIntegrationJobDslExtensionTest
Running InjectedTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.72 sec - in org.jenkinsci.plugins.pretestedintegration.PretestedIntegrationJobDslExtensionTest
Running org.jenkinsci.plugins.pretestedintegration.unit.AbstractSCMBridgeTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 18.057 sec - in org.jenkinsci.plugins.pretestedintegration.unit.AbstractSCMBridgeTest
Running org.jenkinsci.plugins.pretestedintegration.unit.GitIntegrationStrategyTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.013 sec - in org.jenkinsci.plugins.pretestedintegration.unit.GitIntegrationStrategyTest
Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 19.264 sec - in InjectedTest

Results :

Tests run: 16, Failures: 0, Errors: 0, Skipped: 0

[INFO] 
[INFO] --- maven-license-plugin:1.7:process (default) @ pretested-integration ---
[INFO] Generated /Users/simon/Github/praqma/pretested-integration-plugin/target/pretested-integration/WEB-INF/licenses.xml
[INFO] 
[INFO] --- maven-hpi-plugin:1.115:hpi (default-hpi) @ pretested-integration ---
[INFO] Generating /Users/simon/Github/praqma/pretested-integration-plugin/target/pretested-integration/META-INF/MANIFEST.MF
[INFO] Checking for attached .jar artifact ...
[INFO] Generating jar /Users/simon/Github/praqma/pretested-integration-plugin/target/pretested-integration.jar
[INFO] Building jar: /Users/simon/Github/praqma/pretested-integration-plugin/target/pretested-integration.jar
[INFO] Exploding webapp...
[INFO] Copy webapp webResources to /Users/simon/Github/praqma/pretested-integration-plugin/target/pretested-integration
[INFO] Assembling webapp pretested-integration in /Users/simon/Github/praqma/pretested-integration-plugin/target/pretested-integration
[INFO] Generating hpi /Users/simon/Github/praqma/pretested-integration-plugin/target/pretested-integration.hpi
[INFO] Building jar: /Users/simon/Github/praqma/pretested-integration-plugin/target/pretested-integration.hpi
[INFO] 
[INFO] --- maven-failsafe-plugin:2.17:integration-test (default) @ pretested-integration ---
[INFO] Failsafe report directory: /Users/simon/Github/praqma/pretested-integration-plugin/target/failsafe-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.jenkinsci.plugins.pretestedintegration.integration.scm.git.AccumulatedCommitMessageIT
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 81.918 sec - in org.jenkinsci.plugins.pretestedintegration.integration.scm.git.AccumulatedCommitMessageIT
Running org.jenkinsci.plugins.pretestedintegration.integration.scm.git.AccumulatedCommitStrategyIT
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 49.879 sec - in org.jenkinsci.plugins.pretestedintegration.integration.scm.git.AccumulatedCommitStrategyIT
Running org.jenkinsci.plugins.pretestedintegration.integration.scm.git.ChangelessBranchFailsBuildIT
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 10.815 sec - in org.jenkinsci.plugins.pretestedintegration.integration.scm.git.ChangelessBranchFailsBuildIT
Running org.jenkinsci.plugins.pretestedintegration.integration.scm.git.CommitMessagesWithSpecialCharsIT
Tests run: 8, Failures: 0, Errors: 0, Skipped: 2, Time elapsed: 78.059 sec - in org.jenkinsci.plugins.pretestedintegration.integration.scm.git.CommitMessagesWithSpecialCharsIT
Running org.jenkinsci.plugins.pretestedintegration.integration.scm.git.CustomIntegrationBranchIT
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 26.155 sec - in org.jenkinsci.plugins.pretestedintegration.integration.scm.git.CustomIntegrationBranchIT
Running org.jenkinsci.plugins.pretestedintegration.integration.scm.git.EnvVarsIT
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 5.095 sec - in org.jenkinsci.plugins.pretestedintegration.integration.scm.git.EnvVarsIT
Running org.jenkinsci.plugins.pretestedintegration.integration.scm.git.FastForwardSingleCommitsIT
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 77.664 sec - in org.jenkinsci.plugins.pretestedintegration.integration.scm.git.FastForwardSingleCommitsIT
Running org.jenkinsci.plugins.pretestedintegration.integration.scm.git.GeneralBehaviourIT
Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 106.091 sec - in org.jenkinsci.plugins.pretestedintegration.integration.scm.git.GeneralBehaviourIT
Running org.jenkinsci.plugins.pretestedintegration.integration.scm.git.GetCommitCountFromBranchCallbackIT
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.032 sec - in org.jenkinsci.plugins.pretestedintegration.integration.scm.git.GetCommitCountFromBranchCallbackIT
Running org.jenkinsci.plugins.pretestedintegration.integration.scm.git.IntegrationBranchNameRestrictions_IT
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 37.408 sec - in org.jenkinsci.plugins.pretestedintegration.integration.scm.git.IntegrationBranchNameRestrictions_IT
Running org.jenkinsci.plugins.pretestedintegration.integration.scm.git.JENKINS_24754_IT
Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 118.281 sec - in org.jenkinsci.plugins.pretestedintegration.integration.scm.git.JENKINS_24754_IT
Running org.jenkinsci.plugins.pretestedintegration.integration.scm.git.JENKINS_25546_IT
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 66.714 sec - in org.jenkinsci.plugins.pretestedintegration.integration.scm.git.JENKINS_25546_IT
Running org.jenkinsci.plugins.pretestedintegration.integration.scm.git.MatrixProjectCompatabilityTestIT
Tests run: 2, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 12.707 sec - in org.jenkinsci.plugins.pretestedintegration.integration.scm.git.MatrixProjectCompatabilityTestIT
Running org.jenkinsci.plugins.pretestedintegration.integration.scm.git.MultipleScm_threeRepos_IT
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 45.412 sec - in org.jenkinsci.plugins.pretestedintegration.integration.scm.git.MultipleScm_threeRepos_IT
Running org.jenkinsci.plugins.pretestedintegration.integration.scm.git.MultipleScmIT
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.405 sec <<< FAILURE! - in org.jenkinsci.plugins.pretestedintegration.integration.scm.git.MultipleScmIT
verifyOrderOfBuildDataObjects(org.jenkinsci.plugins.pretestedintegration.integration.scm.git.MultipleScmIT)  Time elapsed: 0.405 sec  <<< ERROR!
java.lang.IllegalStateException: Repository already exists: multi-scm-1.git
        at org.eclipse.jgit.internal.storage.file.FileRepository.create(FileRepository.java:268)
        at org.jenkinsci.plugins.pretestedintegration.integration.scm.git.TestUtilsFactory.createRepoWithoutBranches(TestUtilsFactory.java:393)
        at org.jenkinsci.plugins.pretestedintegration.integration.scm.git.MultipleScmIT.verifyOrderOfBuildDataObjects(MultipleScmIT.java:49)

Running org.jenkinsci.plugins.pretestedintegration.integration.scm.git.SquashCommitStrategyIT
Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 114.319 sec - in org.jenkinsci.plugins.pretestedintegration.integration.scm.git.SquashCommitStrategyIT
Running org.jenkinsci.plugins.pretestedintegration.integration.scm.git.TwoBranchHeadsIT
Tests run: 4, Failures: 0, Errors: 0, Skipped: 4, Time elapsed: 0 sec - in org.jenkinsci.plugins.pretestedintegration.integration.scm.git.TwoBranchHeadsIT
Running org.jenkinsci.plugins.pretestedintegration.integration.scm.git.UseAuthorOfLastCommitIT
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 26.285 sec - in org.jenkinsci.plugins.pretestedintegration.integration.scm.git.UseAuthorOfLastCommitIT

Results :

Tests in error: 
  MultipleScmIT.verifyOrderOfBuildDataObjects:49 » IllegalState Repository alrea...

Tests run: 73, Failures: 0, Errors: 1, Skipped: 7

[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] 
[INFO] --- maven-failsafe-plugin:2.17:verify (default) @ pretested-integration ---
[INFO] Failsafe report directory: /Users/simon/Github/praqma/pretested-integration-plugin/target/failsafe-reports
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 14:49 min
[INFO] Finished at: 2017-09-18T16:15:39+02:00
[INFO] Final Memory: 66M/987M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:2.17:verify (default) on project pretested-integration: There are test failures.
[ERROR] 
[ERROR] Please refer to /Users/simon/Github/praqma/pretested-integration-plugin/target/failsafe-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by groenborg** [comment] 2017-09-18 14:28
## Findings
Version: pretested-integration-2.4.1 runs all the tests except for one, which Is a fail on a repository that already exists. This could be caused by some timing issues, however we do not see it as a problem. 


**master** however fails. We have a suspicions that the errors come from version changes is this commit #f5bd0db

**Comment by groenborg** [comment] 2017-09-19 08:10
I will make a new issue containing the finding of the next debugging session, and close this one

**Closed by groenborg** 2017-09-19 08:10 UTC
Labels: Size 3 - large
