### ISSUE TITLE
Plugin crashed with Nullpointerexception in publishing step

### ISSUE THREAD

**Issue by x10an14** [Praqma/pretested-integration-plugin#33] opened 2017-03-22 09:50 UTC
Hey!

I experienced a crash (`NullPointerException`) given by this plugin when used in the `publisher` step.

See below for local/remote git logs (`git show` given in Jenkins output at the bottom),
and JobDSL definition in the middle (below):

Git log-history-graph:
```
[Wed Mar 22 10:49:36 b001cch@b001cch-zbook Bash: 4.2.46 ~/current_or_last_course] (ready/bleh) $ git log ^381c62fd406ef152244383fd1dff94b6c37f26a5 --graph --topo-order --all --decorate
* commit 36147eb1c6fe8bcece17403fe15203881ddda25e (HEAD, origin/ready/bleh, ready/bleh)
| Author: Christian Chavez <christian.chavez@moller.no>
| Date:   Wed Mar 22 10:32:17 2017 +0100
| 
|     Testy
|    
| * commit abdfffc5e36170b421e36f5562008446b13c0f3a (origin/ready/meh, ready/meh)
|/  Author: Christian Chavez <christian.chavez@moller.no>
|   Date:   Wed Mar 22 10:15:53 2017 +0100
|   
|       Meh!
|  
* commit 1d1bd37cf64987df986416a26ad93c353593cf90 (origin/master, origin/HEAD, master)
  Author: Andrey Devyatkin <andrey.a.devyatkin@gmail.com>
  Date:   Tue May 3 18:25:08 2016 +0200
  
      added travis file
      
      Signed-off-by: Andrey Devyatkin <andrey.a.devyatkin@gmail.com>
[Wed Mar 22 10:49:49 b001cch@b001cch-zbook Bash: 4.2.46 ~/current_or_last_course] (ready/bleh) $ 
```

JobDSL:
```
job("${my_folder}/pretested-integration-example") {
	logRotator(30, -1, 1, -1)
	wrappers {
		//colorizeOutput()
		timestamps()
		timeout {
			elastic(200, 3, 60)
			failBuild()
			//writeDescription("Aborted!")
		}
	}

	scm {
		// Adds a Git SCM source.
		git {
			remote {
				name('origin')
				url("${githubssh}:x10an14/roadshow.git")
				credentials('jenkins')
			}
			branch('*/ready/*')
			extensions {
				cleanBeforeCheckout()
			}
		}
	}

	triggers {
		scm ('* * * * *') // Every minute
	}

	steps {
		shell('echo \'\\n\\nyippie-kay-yay!\\n\\n\'')
		// shell('git log -n 1')
		// shell('git diff HEAD~1..HEAD')
		shell('git show HEAD') // does the same as the two above
		shell('echo \'\\n\\n\'')
		shell('./gradlew check war test jenkinstest jacoco staticanalysis')
	}

	publishers {
		// Collect code coverage report
		jacocoCodeCoverage()
		// Collect unit test results
		archiveJunit('build/test-results/*.xml')
		// Collect PMD report
		pmd('build/reports/pmd/*.xml')
		// Collect tasks statistics
		tasks('**/*', '', 'FIXME', 'TODO', 'LOW', true)
		// Collect check style report
		checkstyle('build/reports/checkstyle/*.xml')
		// Collect compilation warnings
		warnings(['Java Compiler (javac)'])
		pretestedIntegration()
	}
}
```

Jenkins output:
```
10:33:10 Started by an SCM change
10:33:10 Building remotely on 721c1253be7f-aa87cd1c (utility-slave java swarm alpine linux 3.3 docker) in workspace /root/workspace/x10-generated-jobs/pretested-integration-example
10:33:10  > git rev-parse --is-inside-work-tree # timeout=10
10:33:10 Fetching changes from the remote Git repository
10:33:10  > git config remote.origin.url git@github.com:x10an14/roadshow.git # timeout=10
10:33:10 Cleaning workspace
10:33:10  > git rev-parse --verify HEAD # timeout=10
10:33:10 Resetting working tree
10:33:10  > git reset --hard # timeout=10
10:33:10  > git clean -fdx # timeout=10
10:33:10 Fetching upstream changes from git@github.com:x10an14/roadshow.git
10:33:10  > git --version # timeout=10
10:33:10 using GIT_SSH to set credentials 
10:33:10  > git fetch --tags --progress git@github.com:x10an14/roadshow.git +refs/heads/*:refs/remotes/origin/*
10:33:11 Seen branch in repository origin/master
10:33:11 Seen branch in repository origin/ready/bleh
10:33:11 Seen branch in repository origin/ready/meh
10:33:11 Seen 3 remote branches
10:33:11 Checking out Revision 36147eb1c6fe8bcece17403fe15203881ddda25e (origin/ready/bleh)
10:33:11  > git config core.sparsecheckout # timeout=10
10:33:11  > git checkout -f 36147eb1c6fe8bcece17403fe15203881ddda25e
10:33:11 First time build. Skipping changelog.
10:33:11 [pretested-integration-example] $ /bin/sh -xe /tmp/hudson4628239782322578846.sh
10:33:11 + echo \n\nyippie-kay-yay!\n\n
10:33:11 
10:33:11 
10:33:11 yippie-kay-yay!
10:33:11 
10:33:11 
10:33:11 [pretested-integration-example] $ /bin/sh -xe /tmp/hudson6540027255860273176.sh
10:33:11 + git show HEAD
10:33:11 commit 36147eb1c6fe8bcece17403fe15203881ddda25e
10:33:11 Author: Christian Chavez <christian.chavez@moller.no>
10:33:11 Date:   Wed Mar 22 10:32:17 2017 +0100
10:33:11 
10:33:11     Testy
10:33:11 
10:33:11 diff --git a/taskchecker.py b/taskchecker.py
10:33:11 index 0b5b668..823a933 100644
10:33:11 --- a/taskchecker.py
10:33:11 +++ b/taskchecker.py
10:33:11 @@ -1,5 +1,6 @@
10:33:11 -from subprocess import Popen, PIPE, call
10:33:11 +from subprocess import Popen, PIPE
10:33:11  import re
10:33:11 +from sys import exit
10:33:11  
10:33:11  pipe = Popen(["git", "log", "-1"], stdout=PIPE)
10:33:11  gitLog = pipe.communicate()[0]
10:33:11 @@ -8,4 +9,4 @@ matchObj = re.search(r"Task\s+(\d+)",gitLog, flags=0)
10:33:11  
10:33:11  if not matchObj:
10:33:11      call("echo 'Your commit message needs to contain Task XXXX where X is number.'",shell=1)
10:33:11 -    call(["exit","1"], shell=1) 
10:33:11 +    exit(1)
10:33:11 [pretested-integration-example] $ /bin/sh -xe /tmp/hudson3578926724390175896.sh
10:33:11 + echo \n\n
10:33:11 
10:33:11 
10:33:11 
10:33:11 [pretested-integration-example] $ /bin/sh -xe /tmp/hudson1438001211977089960.sh
10:33:11 + ./gradlew check war test jenkinstest jacoco staticanalysis
10:33:18 Property 'tomcatUsername' not defined
10:33:18 Property 'tomcatPassword' not defined
10:33:19 :compileJavawarning: [options] bootstrap class path not set in conjunction with -source 1.6
10:33:21 1 warning
10:33:21 
10:33:21 :processResources UP-TO-DATE
10:33:21 :classes
10:33:21 :checkstyleMain[ant:checkstyle] /root/workspace/x10-generated-jobs/pretested-integration-example/src/main/java/net/praqma/roadshow/Calculator.java:0: Copyright is missing or malformed.
10:33:23 [ant:checkstyle] /root/workspace/x10-generated-jobs/pretested-integration-example/src/main/java/net/praqma/roadshow/Calculator.java:12: warning: Wrong order for 'net.praqma.roadshow.model.CalculatorModel' import.
10:33:23 [ant:checkstyle] /root/workspace/x10-generated-jobs/pretested-integration-example/src/main/java/net/praqma/roadshow/Calculator.java:15: warning: First sentence should end with a period.
10:33:23 [ant:checkstyle] /root/workspace/x10-generated-jobs/pretested-integration-example/src/main/java/net/praqma/roadshow/Calculator.java:18: Line is longer than 100 characters (found 165).
10:33:23 [ant:checkstyle] /root/workspace/x10-generated-jobs/pretested-integration-example/src/main/java/net/praqma/roadshow/Calculator.java:21: TODO is preferred to FIXME.  e.g. "TODO(johndoe): Refactor when v2 is released."
10:33:23 [ant:checkstyle] /root/workspace/x10-generated-jobs/pretested-integration-example/src/main/java/net/praqma/roadshow/Calculator.java:32: Line is longer than 100 characters (found 122).
10:33:23 [ant:checkstyle] /root/workspace/x10-generated-jobs/pretested-integration-example/src/main/java/net/praqma/roadshow/Calculator.java:37: Line is longer than 100 characters (found 121).
10:33:23 [ant:checkstyle] /root/workspace/x10-generated-jobs/pretested-integration-example/src/main/java/net/praqma/roadshow/model/CalculatorModel.java:0: Copyright is missing or malformed.
10:33:23 [ant:checkstyle] /root/workspace/x10-generated-jobs/pretested-integration-example/src/main/java/net/praqma/roadshow/model/CalculatorModelImpl.java:0: Copyright is missing or malformed.
10:33:23 [ant:checkstyle] /root/workspace/x10-generated-jobs/pretested-integration-example/src/main/java/net/praqma/roadshow/model/CalculatorModelImpl.java:3: Missing a Javadoc comment.
10:33:23 [ant:checkstyle] /root/workspace/x10-generated-jobs/pretested-integration-example/src/main/java/net/praqma/roadshow/model/CalculatorModelImpl.java:9:15: 'if' is not followed by whitespace.
10:33:23 [ant:checkstyle] /root/workspace/x10-generated-jobs/pretested-integration-example/src/main/java/net/praqma/roadshow/model/CalculatorModelImpl.java:9:39: '==' is not preceded with whitespace.
10:33:23 [ant:checkstyle] /root/workspace/x10-generated-jobs/pretested-integration-example/src/main/java/net/praqma/roadshow/model/CalculatorModelImpl.java:9:41: '==' is not followed by whitespace.
10:33:23 [ant:checkstyle] /root/workspace/x10-generated-jobs/pretested-integration-example/src/main/java/net/praqma/roadshow/model/CalculatorModelImpl.java:11:22: 'if' is not followed by whitespace.
10:33:23 [ant:checkstyle] /root/workspace/x10-generated-jobs/pretested-integration-example/src/main/java/net/praqma/roadshow/model/CalculatorModelImpl.java:11:58: '==' is not preceded with whitespace.
10:33:23 [ant:checkstyle] /root/workspace/x10-generated-jobs/pretested-integration-example/src/main/java/net/praqma/roadshow/model/CalculatorModelImpl.java:11:60: '==' is not followed by whitespace.
10:33:23 [ant:checkstyle] /root/workspace/x10-generated-jobs/pretested-integration-example/src/main/java/net/praqma/roadshow/model/CalculatorModelImpl.java:25:15: 'if' is not followed by whitespace.
10:33:23 
10:33:23 Checkstyle rule violations were found. See the report at: file:///root/workspace/x10-generated-jobs/pretested-integration-example/build/reports/checkstyle/main.xml
10:33:23 :compileTestJavawarning: [options] bootstrap class path not set in conjunction with -source 1.6
10:33:23 1 warning
10:33:23 
10:33:23 :processTestResources UP-TO-DATE
10:33:23 :testClasses
10:33:23 :checkstyleTest[ant:checkstyle] /root/workspace/x10-generated-jobs/pretested-integration-example/src/test/java/net/praqma/roadshow/functional/TestAdditionRC.java:0: Copyright is missing or malformed.
10:33:24 [ant:checkstyle] /root/workspace/x10-generated-jobs/pretested-integration-example/src/test/java/net/praqma/roadshow/functional/TestAdditionRC.java:4: warning: Wrong order for 'org.apache.commons.lang3.StringUtils' import.
10:33:24 [ant:checkstyle] /root/workspace/x10-generated-jobs/pretested-integration-example/src/test/java/net/praqma/roadshow/functional/TestAdditionRC.java:6: warning: Wrong order for 'org.junit.Assert.*' import.
10:33:24 [ant:checkstyle] /root/workspace/x10-generated-jobs/pretested-integration-example/src/test/java/net/praqma/roadshow/functional/TestAdditionRC.java:10: Missing a Javadoc comment.
10:33:24 [ant:checkstyle] /root/workspace/x10-generated-jobs/pretested-integration-example/src/test/java/net/praqma/roadshow/functional/TestAdditionRC.java:11:1: File contains tab characters (this is the first instance).
10:33:24 [ant:checkstyle] /root/workspace/x10-generated-jobs/pretested-integration-example/src/test/java/net/praqma/roadshow/functional/TestAdditionRC.java:25: Line is longer than 100 characters (found 123).
10:33:24 [ant:checkstyle] /root/workspace/x10-generated-jobs/pretested-integration-example/src/test/java/net/praqma/roadshow/functional/TestAdditionRC.java:25:58: ',' is not followed by whitespace.
10:33:24 [ant:checkstyle] /root/workspace/x10-generated-jobs/pretested-integration-example/src/test/java/net/praqma/roadshow/functional/TestAdditionRC.java:25:91: ',' is not followed by whitespace.
10:33:24 [ant:checkstyle] /root/workspace/x10-generated-jobs/pretested-integration-example/src/test/java/net/praqma/roadshow/unit/TestCalculatorModel.java:0: Copyright is missing or malformed.
10:33:24 [ant:checkstyle] /root/workspace/x10-generated-jobs/pretested-integration-example/src/test/java/net/praqma/roadshow/unit/TestCalculatorModel.java:0: File does not end with a newline.
10:33:24 [ant:checkstyle] /root/workspace/x10-generated-jobs/pretested-integration-example/src/test/java/net/praqma/roadshow/unit/TestCalculatorModel.java:9: Missing a Javadoc comment.
10:33:24 [ant:checkstyle] /root/workspace/x10-generated-jobs/pretested-integration-example/src/test/java/net/praqma/roadshow/unit/TestCalculatorModel.java:22:47: ',' is not followed by whitespace.
10:33:24 [ant:checkstyle] /root/workspace/x10-generated-jobs/pretested-integration-example/src/test/java/net/praqma/roadshow/unit/TestCalculatorModel.java:23:25: ',' is not followed by whitespace.
10:33:24 [ant:checkstyle] /root/workspace/x10-generated-jobs/pretested-integration-example/src/test/java/net/praqma/roadshow/unit/TestCalculatorModel.java:23:36: ',' is not followed by whitespace.
10:33:24 [ant:checkstyle] /root/workspace/x10-generated-jobs/pretested-integration-example/src/test/java/net/praqma/roadshow/unit/TestCalculatorModel.java:28:60: ',' is not followed by whitespace.
10:33:24 [ant:checkstyle] /root/workspace/x10-generated-jobs/pretested-integration-example/src/test/java/net/praqma/roadshow/unit/TestCalculatorModel.java:35:37: ',' is not followed by whitespace.
10:33:24 [ant:checkstyle] /root/workspace/x10-generated-jobs/pretested-integration-example/src/test/java/net/praqma/roadshow/unit/TestCalculatorModel.java:47:50: ',' is not followed by whitespace.
10:33:24 [ant:checkstyle] /root/workspace/x10-generated-jobs/pretested-integration-example/src/test/java/net/praqma/roadshow/unit/TestCalculatorModel.java:53:47: ',' is not followed by whitespace.
10:33:24 [ant:checkstyle] /root/workspace/x10-generated-jobs/pretested-integration-example/src/test/java/net/praqma/roadshow/unit/TestCalculatorModel.java:65:51: 'cast' is not followed by whitespace.
10:33:24 [ant:checkstyle] /root/workspace/x10-generated-jobs/pretested-integration-example/src/test/java/net/praqma/roadshow/unit/TestCalculatorModel.java:66:51: 'cast' is not followed by whitespace.
10:33:24 [ant:checkstyle] /root/workspace/x10-generated-jobs/pretested-integration-example/src/test/java/net/praqma/roadshow/unit/TestCalculatorModel.java:71:50: 'cast' is not followed by whitespace.
10:33:24 
10:33:24 Checkstyle rule violations were found. See the report at: file:///root/workspace/x10-generated-jobs/pretested-integration-example/build/reports/checkstyle/test.xml
10:33:24 :findbugsMain
10:33:30 FindBugs rule violations were found. See the report at: file:///root/workspace/x10-generated-jobs/pretested-integration-example/build/reports/findbugs/main.xml
10:33:30 :findbugsTest
10:33:35 FindBugs rule violations were found. See the report at: file:///root/workspace/x10-generated-jobs/pretested-integration-example/build/reports/findbugs/test.xml
10:33:35 :jdependMain
10:33:35 :jdependTest
10:33:35 :pmdMain
10:33:37 :pmdTest
10:33:37 :test
10:33:40 :check
10:33:40 :war
10:33:41 :jenkinstest
10:33:41 :jacocoTestReport
10:33:42 :staticAnalysis
10:33:42 
10:33:42 BUILD SUCCESSFUL
10:33:42 
10:33:42 Total time: 30.383 secs
10:33:42 [JaCoCo plugin] Collecting JaCoCo coverage data...
10:33:42 [JaCoCo plugin] **/target/**.exec;**/classes;**/src/main/java; locations are configured
10:33:42 [JaCoCo plugin] Number of found exec files for pattern **/target/**.exec: 0
10:33:42 [JaCoCo plugin] Saving matched execfiles:  
10:33:42 [JaCoCo plugin] Saving matched class directories for class-pattern: **/classes:  /root/workspace/x10-generated-jobs/pretested-integration-example/build/classes /root/workspace/x10-generated-jobs/pretested-integration-example/build/reports/tests/classes
10:33:42 [JaCoCo plugin] Saving matched source directories for source-pattern: **/src/main/java:  /root/workspace/x10-generated-jobs/pretested-integration-example/src/main/java
10:33:42 [JaCoCo plugin] Loading inclusions files..
10:33:42 [JaCoCo plugin] inclusions: [**/*.class]
10:33:42 [JaCoCo plugin] exclusions: [**/*Test*]
10:33:42 [JaCoCo plugin] Thresholds: JacocoHealthReportThresholds [minClass=0, maxClass=0, minMethod=0, maxMethod=0, minLine=0, maxLine=0, minBranch=0, maxBranch=0, minInstruction=0, maxInstruction=0, minComplexity=0, maxComplexity=0]
10:33:42 [JaCoCo plugin] Publishing the results..
10:33:42 [JaCoCo plugin] Loading packages..
10:33:42 [JaCoCo plugin] Done.
10:33:42 [JaCoCo plugin] Overall coverage: class: 0, method: 0, line: 0, branch: 0, instruction: 0
10:33:42 Recording test results
10:33:42 Collecting PMD analysis files...
10:33:42 [PMD] Finding all files that match the pattern build/reports/pmd/*.xml
10:33:42 [PMD] Parsing 2 files in /root/workspace/x10-generated-jobs/pretested-integration-example
10:33:42 [PMD] Successfully parsed file /root/workspace/x10-generated-jobs/pretested-integration-example/build/reports/pmd/main.xml with 0 unique warnings and 0 duplicates.
10:33:42 [PMD] Successfully parsed file /root/workspace/x10-generated-jobs/pretested-integration-example/build/reports/pmd/test.xml with 0 unique warnings and 0 duplicates.
10:33:54 [TASKS] Scanning folder '/root/workspace/x10-generated-jobs/pretested-integration-example' for files matching the pattern '**/*' - excludes: 
10:33:54 [TASKS] Found 99 files to scan for tasks
10:33:54 Found 24 open tasks.
10:33:55 Collecting checkstyle analysis files...
10:33:56 [CHECKSTYLE] Finding all files that match the pattern build/reports/checkstyle/*.xml
10:33:56 [CHECKSTYLE] Parsing 2 files in /root/workspace/x10-generated-jobs/pretested-integration-example
10:33:56 [CHECKSTYLE] Successfully parsed file /root/workspace/x10-generated-jobs/pretested-integration-example/build/reports/checkstyle/main.xml with 17 unique warnings and 0 duplicates.
10:33:56 [CHECKSTYLE] Successfully parsed file /root/workspace/x10-generated-jobs/pretested-integration-example/build/reports/checkstyle/test.xml with 38 unique warnings and 0 duplicates.
10:33:56 Parsing warnings in console log with parser Java Compiler (javac)
10:33:56 [PREINT] Performing pre-verified post build steps
10:33:56 Caught NullPointerException during post-checkout. Failing build.
10:33:56 java.lang.NullPointerException
10:33:56 	at org.jenkinsci.plugins.pretestedintegration.PretestedIntegrationPostCheckout.getScmBridge(PretestedIntegrationPostCheckout.java:45)
10:33:56 	at org.jenkinsci.plugins.pretestedintegration.PretestedIntegrationPostCheckout.perform(PretestedIntegrationPostCheckout.java:69)
10:33:56 	at hudson.tasks.BuildStepMonitor$3.perform(BuildStepMonitor.java:45)
10:33:56 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
10:33:56 	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)
10:33:56 	at hudson.model.Build$BuildExecution.post2(Build.java:185)
10:33:56 	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:665)
10:33:56 	at hudson.model.Run.execute(Run.java:1753)
10:33:56 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
10:33:56 	at hudson.model.ResourceController.execute(ResourceController.java:98)
10:33:56 	at hudson.model.Executor.run(Executor.java:404)
10:33:56 ERROR: Step ‘Pretested Integration Publisher’ failed: Unexpected error. Trace written to log.
10:33:56 [BFA] Scanning build for known causes...
10:33:56 [BFA] No failure causes found
10:33:56 [BFA] Done. 0s
10:33:56 Finished: FAILURE
```

**Comment by MadsNielsen** [comment] 2017-03-22 12:47
Hey @x10an14 

Thanks for this report. This is a know issue, currently pretested integration does not work with the pipeline job type. We're looking for sponsors to fix and implement this issue. 

It's a fairly large task to get it working properly with workflow/pipeline due to our dependence on the git client that is configured by the git plugin. 

I'll have a chat around the office to see if we can pan out a plan to get the support in.

Best regards,
Mads

**Comment by MadsNielsen** [comment] 2017-03-22 12:50
The issue is also described in #30

**Comment by buep** [comment] 2017-03-26 19:06
closing as dublicate by #30 - it will be fixed if we implement pipeline support.

**Closed by buep** 2017-03-26 19:06 UTC
