### ISSUE TITLE
Support for maven projects type (our case 12361)

### ISSUE THREAD

**Issue by lakruzz** [Praqma/pretested-integration-plugin#7] opened 2016-02-16 13:37 UTC
[Jenkins issue 25805](https://issues.jenkins-ci.org/browse/JENKINS-25805)

For "maven2/3 projects" only (ok for "free-style software projects").
Section 'Use pretested integration' does not appear in the Job configuration page of "maven2/3 projects".
While the 'Pretested Integration post-build' is available in the 'Add post-build action' dropdown, section 'Use pretested integration' does not appear in the Job configuration page.
Why 'Use pretested integration' doesn't show up? Conflict with another plugin? Something missing?

**Comment by buep** [comment] 2016-06-22 09:40
Please groom

**Comment by praqma-thi** [comment] 2016-06-22 11:12
There's a few points in the code where we check if the project is specifically a FreeStyleProject (or, worryingly, a Matrix project).
We'd just have to include/allow the MavenModuleSet in these checks and test that it works as intended. I've little knowledge of the MavenModuleSet itself so I'm not sure what bad stuff to expect from allowing Pretested to run in one. 

I'd say we just allow MavenModuleSets in the checks so we can configure it in a test Maven project, take it for a spin and see if it explodes/how difficult it is to get it working. If everything goes smoothly it might even end up working at the end of that, though that may be a little optimistic.

So; 

| Enable for MavenModuleSet | Set up a test job/repo to play with | Try and get it working |
|---------------------------|-------------------------------------|------------------------|
| Small/Medium               | Small                               | Depends how much we want to dedicate to it. Medium? |

**Comment by buep** [comment] 2016-06-22 11:29
Good stuff, but just got an idea.... what if we changed our code to allow both freestyle and maven projects (only those) and then more or less duplicated all our tests (which I think covers more or less everything) to run for maven project types? Wouldn't that easily show problems?

How much time do you think it would take to prepare such a test-suite?

**Comment by praqma-thi** [comment] 2016-06-22 11:43
That's a great idea, I just took a look at the tests and there's very liberal use of FreeStyleProject/Build throughout all of them, for setup and asserts and whatnot. We could replace that all with use of AbstractProject/Build, consolidate creation to some class where we can choose to either construct FreeStyle or Maven projects. 

It'd be a nice opportunity to clean up while we're there as well, but I can see it adding a lot of work, probably more than doubling it. I think we should do the short timebox where we just see what happens when we run it as part of a Maven job. If that doesn't go too horrendously bad, we should follow it up with running all the tests against it.

**Comment by buep** [comment] 2016-06-22 12:10
> I think we should do the short timebox where we just see what happens when we run it as part of a Maven job.

As long as this just is done as writing a tests or few tests it is fine. In this stage copying could be okay of existing tests.

By duplicating tests, I also as you suggest meant parametrizing existing and run them with the two job types as parameters giving twice as many tests as now.


So create a new issues for writing some automated tests for Maven project? Estimate that. Think this issue becomes a briefing now instead.

**Comment by praqma-thi** [comment] 2016-06-24 12:29
Copying the tests is someting I'd rather not get into. There's a _lot_ of tests.
Rewriting the existing ones to accept AbstractProject so we can pass in both Maven and FreeStyle projects is the way to go, but due to the sheer volume of tests and the liberal use of FreeStyleProject in them, it could take multiple days.

It's the right thing to do but it's also quite intense. If this is going into Josra, do we have any members wanting this or is this just for the open source community?

**Comment by lakruzz** [comment] 2016-06-26 07:24
I don't know the original reporter on this issue: [Jenkins issue 25805](https://issues.jenkins-ci.org/browse/JENKINS-25805) but we should definitely get some funding before we continue

**Comment by lakruzz** [comment] 2016-06-26 07:33
Hi Al Ferguson

Poking you in context of:

https://issues.jenkins-ci.org/browse/JENKINS-25872

now continued in:

https://github.com/Praqma/pretested-integration-plugin/issues/4

Al, are you still interested in this issue?..

**Comment by buep** [comment] 2016-06-28 23:02
What do Jenkins jira issue 25872 and 25802 have to do with each other?

Either how we are only talking about investigating the effort on this change, so we don't have any estimates yet - only timeboxes.

But actually, I'm having second thought.... I do not recommend to support the Maven project type - I would not recommend to use, always use freestyle job. I know some are using the Maven projects, but they should convert to freestyle.

So will we support a job type we do not recommend to use?

**Comment by buep** [comment] 2017-05-17 15:31
I'm closing this, as we now have SoW out based on discussions from the Code Alliance 6th gathering that I think will fix this.
See #37

**Closed by buep** 2017-05-17 15:31 UTC
Labels: Prio 3 - could have, Size 0 - Briefing
